webservers:
  hosts:
    stage1:
      ansible_user: deploy
      ansible_port: 22
      ansible_host: {{cookiecutter.ssh_host_stage}}
      stage_name: stage
      stage_wp_env: staging
      stage_domain: {{cookiecutter.domain_stage}}
